spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test


# 配置mybatis规则
mybatis:
  mapper-locations: classpath:mapper/*.xml  #sql映射文件位置
  type-aliases-package: com.example.demo10_02_one.bean
  configuration:
    map-underscore-to-camel-case: true

